import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import inlineImportPlugin from "esbuild-plugin-inline-import";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

async function main() {
	const context = await esbuild.context({
		banner: {
			js: banner,
		},
		entryPoints: ['main.ts'],
		bundle: true,
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/closebrackets',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/comment',
			'@codemirror/fold',
			'@codemirror/gutter',
			'@codemirror/highlight',
			'@codemirror/history',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/matchbrackets',
			'@codemirror/panel',
			'@codemirror/rangeset',
			'@codemirror/rectangular-selection',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/stream-parser',
			'@codemirror/text',
			'@codemirror/tooltip',
			'@codemirror/view',
			...builtins
		],
		format: 'cjs',
		target: 'es2020',
		logLevel: 'info',
		sourcemap: prod ? false : 'inline',
		treeShaking: true,
		outfile: 'main.js',
		plugins: [
			inlineImportPlugin()
		],
		minify: prod,
	});

	if (prod) {
		await context.rebuild();
		await context.dispose();
	} else {
		await context.watch();
	}
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
